import { Bot, Send, X } from 'lucide-react'
import { useState } from 'react'
import { askMentor } from '../../services/chatApi'
import { useAuthStore } from '../../store/authStore'
import { useRoadmapStore } from '../../store/roadmapStore'
export default function ChatWindow({ onClose }) {
  const user = useAuthStore(s => s.user); const roadmap = useRoadmapStore(s => s.roadmap)
  const [messages,setMessages]=useState([{role:'assistant',content:`Hi ${user?.name?.split(' ')[0] || 'there'} — I can help you unblock your ${user?.career_target || 'learning'} path. What are you working on?`}]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false)
  const send=async e=>{e.preventDefault(); if(!input.trim()||busy)return; const question=input.trim(); setInput(''); setMessages(m=>[...m,{role:'user',content:question}]); setBusy(true); try { const gaps=(roadmap?.nodes||[]).filter(n=>n.status==='weak_gap').map(n=>n.topic); const response=await askMentor({user_id:user?.id,message:question,current_topic:gaps[0]||'your roadmap',career_target:user?.career_target||'Full Stack Engineer',weak_gaps:gaps}); setMessages(m=>[...m,{role:'assistant',content:response.reply}]) } catch { setMessages(m=>[...m,{role:'assistant',content:'I’m temporarily offline, but break the problem into input, output, and one small test case. Then tell me where it gets fuzzy.'}]) } finally {setBusy(false)} }
  return <div className="fixed inset-0 z-40 flex justify-end bg-slate-950/50"><section className="flex h-full w-full max-w-md flex-col border-l border-line bg-[#0d192b] shadow-2xl"><header className="flex items-center justify-between border-b border-line p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-400 text-slate-950"><Bot size={20}/></span><div><h2 className="font-bold">AI Mentor</h2><p className="text-xs text-emerald-300">Context-aware · ready to help</p></div></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-800"><X size={19}/></button></header><div className="flex-1 space-y-4 overflow-y-auto p-5">{messages.map((m,i)=><div key={i} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${m.role==='user'?'ml-auto bg-sky-400 text-slate-950':'bg-slate-800 text-slate-200'}`}>{m.content}</div>)}{busy&&<div className="w-fit rounded-2xl bg-slate-800 px-4 py-3 text-sm text-slate-400">Thinking with your roadmap context…</div>}</div><form onSubmit={send} className="flex gap-2 border-t border-line p-4"><input className="field" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a learning question…"/><button className="btn-primary px-3" aria-label="Send"><Send size={18}/></button></form></section></div>
}
